### ISSUE TITLE
What's with the DLLs?

### ISSUE THREAD

**Issue by indianaliam1** [TheGameratorT/NDS_Banner_Editor#1]
It keeps whinging about numerous DLLs when launching.

**Comment by TheGameratorT** [comment]
Use version 1.0 until this has been fixed.

**Comment by indianaliam1** [comment]
Thanks man, if you need any help with the stuff it's probably the way you compiled it, but it's not my code so just guessing, good luck!

**Comment by TheGameratorT** [comment]
Yeah, I am aware. I used to statically build the .exes to avoid this, but then I formatted the computer and I didn't have the Static Qt anymore, so when I fixed an issue, I uploaded a fix with the DLLs but apparently it only works for me. Thanks for offering help, but I think I won't need it.
Sorry for the trouble.
I will close this issue when it gets fixed.

**Comment by indianaliam1** [comment]
Yeah even after sourcing all of the DLLs, it was still going on about it not being able to start.

**Comment by TheGameratorT** [comment]
The issue has been fixed in release 1.2.1.
https://github.com/TheGameratorT/NDS_Banner_Editor/releases/tag/1.2.1
